<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
  </PropertyGroup>
</Project>
