using System.Globalization;
using System.Windows.Markup;

namespace NaraNote.App.Localization;

public static class UiText
{
    private static readonly string SystemLanguage = SelectLanguage(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName);
    public static string Language { get; private set; } = SystemLanguage;

    public static void SetLanguage(string? preference)
    {
        Language = string.Equals(preference, "system", StringComparison.OrdinalIgnoreCase)
            ? SystemLanguage
            : SelectLanguage(preference ?? "en");
        var cultureName = Language switch { "fr" => "fr-FR", "es" => "es-ES", "vi" => "vi-VN", "ko" => "ko-KR", _ => "en-US" };
        CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo(cultureName);
        CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.CurrentUICulture;
    }

    public static string Get(string key) =>
        Catalog.TryGetValue(Language, out var language) && language.TryGetValue(key, out var value)
            ? value
            : English.TryGetValue(key, out var fallback) ? fallback : key;

    public static string Format(string key, params object[] args) => string.Format(CultureInfo.CurrentCulture, Get(key), args);

    private static string SelectLanguage(string language) => language is "en" or "fr" or "es" or "vi" or "ko" ? language : "en";

    private static readonly Dictionary<string, string> English = new()
    {
        ["Settings"]="Settings", ["Ok"]="OK", ["Cancel"]="Cancel", ["Default"]="Default", ["Browse"]="Browse…", ["Language"]="Language", ["SystemDefault"]="System default",
        ["Reminder"]="Reminder", ["ReminderEdit"]="Edit reminder…", ["ReminderMenu"]="Reminder…", ["ReminderDisable"]="Disable reminder",
        ["ReminderDescription"]="Choose when you want to be reminded.", ["Date"]="Date", ["Time"]="Time", ["Use24Hour"]="24-hour time",
        ["AM"]="AM", ["PM"]="PM", ["Hour"]="Hour", ["Hour023"]="Hour (0–23)", ["Hour112"]="Hour (1–12)", ["Minute059"]="Minute (0–59)",
        ["Repeat"]="Repeat", ["RepeatOnce"]="Once", ["RepeatDaily"]="Daily at the same time", ["RepeatWeekly"]="Weekly at the same time", ["RepeatWeekdays"]="Selected weekdays at the same time",
        ["AutoHide"]="Hide note until reminder", ["AutoHideDescription"]="The note will reappear when the reminder fires.",
        ["Sun"]="Sun", ["Mon"]="Mon", ["Tue"]="Tue", ["Wed"]="Wed", ["Thu"]="Thu", ["Fri"]="Fri", ["Sat"]="Sat",
        ["CurrentNote"]="Current note", ["Font"]="Font", ["FontSize"]="Font size", ["Color"]="Color", ["PenColor"]="Pen color", ["PenThickness"]="Pen thickness", ["PenThicknessInput"]="Pen thickness (1–10)",
        ["GeneralSettings"]="General settings", ["UseTray"]="Use system tray", ["RunAtStartup"]="Run at Windows startup", ["ReminderSound"]="Reminder alarm sound", ["ReminderWavPath"]="Reminder WAV file path",
        ["NewNoteHotKey"]="New note global shortcut", ["ToggleNotesHotKey"]="Show/hide notes global shortcut",
        ["NewNote"]="New note", ["ShowAll"]="Show all", ["ShowAllHidden"]="Show all ({0} hidden)", ["HideAll"]="Hide all", ["Exit"]="Exit",
        ["DirtyExport"]="Modified since the saved file", ["AlwaysOnTop"]="Always on top", ["DisableAlwaysOnTop"]="Disable always on top", ["Menu"]="Menu", ["CloseNote"]="Close this note",
        ["Soon"]="Reminder due", ["RemainingDays"]="{0}d {1}h {2}m remaining", ["RemainingHours"]="{0}h {1}m remaining", ["RemainingMinutes"]="{0}m remaining", ["RemainingSeconds"]="{0}s remaining",
        ["TextMode"]="Text mode", ["PenMode"]="Pen mode", ["EraserMode"]="Eraser mode", ["SyntaxHighlighting"]="Syntax highlighting", ["AutoDetect"]="Auto detect", ["PlainText"]="Plain text",
        ["SaveNote"]="Save current note", ["SaveAs"]="Save as", ["HideNote"]="Hide note", ["Undo"]="Undo", ["Redo"]="Redo", ["Cut"]="Cut", ["Copy"]="Copy", ["Paste"]="Paste", ["Delete"]="Delete", ["SelectAll"]="Select all",
        ["NoteColor"]="Note color", ["Yellow"]="Yellow", ["LightGreen"]="Light green", ["SkyBlue"]="Sky blue", ["Pink"]="Pink", ["Orange"]="Orange", ["LightPurple"]="Light purple", ["LightGray"]="Light gray",
        ["Black"]="Black", ["DarkGray"]="Dark gray", ["Red"]="Red", ["Blue"]="Blue", ["Green"]="Green", ["Purple"]="Purple",
        ["VeryThin"]="Very thin", ["Thin"]="Thin", ["Normal"]="Normal", ["Thick"]="Thick", ["VeryThick"]="Very thick",
        ["UnexpectedError"]="The operation could not be completed. Check the log for details.", ["PenThicknessError"]="Enter a pen thickness from 1 to 10.", ["HotKeyError"]="Enter shortcuts in a format such as Ctrl+Alt+N.", ["SoundMissing"]="The selected alarm sound file could not be found.", ["FontSizeError"]="Enter a font size from 8 to 72.",
        ["SelectAlarmSound"]="Select reminder alarm sound", ["WavFilter"]="WAV audio (*.wav)|*.wav", ["TimeError24"]="Enter an hour from 0 to 23 and minutes from 0 to 59.", ["TimeError12"]="Enter an hour from 1 to 12 and minutes from 0 to 59.", ["WeekdayError"]="Select at least one weekday.",
        ["LargeTextError"]="Text files larger than 5 MB cannot be inserted.", ["ReadFileError"]="The file could not be read.", ["OpenImageError"]="The image could not be opened.", ["AttachmentMissing"]="The attached file could not be found.", ["AttachmentOpenError"]="The attached file could not be opened.",
        ["SaveDialogTitle"]="Save current note", ["NaraNoteFilter"]="NaraNote document (*.naranote)|*.naranote|Text file (*.txt)|*.txt", ["TextFilter"]="Text file (*.txt)|*.txt|NaraNote document (*.naranote)|*.naranote",
        ["LossWarning"]="Saving in this format includes text only. Drawings, images, and attachments will not be included.\n\nDo you want to continue?", ["ObjectsExcluded"]="Objects will be excluded", ["SaveError"]="The note could not be saved. Check the destination and file permissions.",
        ["ExternalChangedDirty"]="The linked file changed outside NaraNote.\n\nReloading will replace unsaved changes in this note. Reload it?", ["ExternalChanged"]="The linked file changed outside NaraNote. Reload it?", ["ReloadError"]="The changed file could not be reloaded. Check its format and permissions."
    };

    private static readonly Dictionary<string, Dictionary<string, string>> Catalog = new()
    {
        ["en"] = English,
        ["ko"] = Override(
            ("Settings","설정"),("Ok","확인"),("Cancel","취소"),("Default","기본"),("Browse","찾기…"),("Reminder","리마인더"),("ReminderEdit","리마인더 변경…"),("ReminderMenu","리마인더…"),("ReminderDisable","리마인더 해제"),("ReminderDescription","알림을 받을 날짜와 시간을 선택하세요."),("Date","날짜"),("Time","시간"),("Use24Hour","24시간제"),("AM","오전"),("PM","오후"),("Hour","시"),("Hour023","시 (0~23)"),("Hour112","시 (1~12)"),("Minute059","분 (0~59)"),("Repeat","반복"),("RepeatOnce","한 번"),("RepeatDaily","매일 같은 시간"),("RepeatWeekly","매주 같은 시간"),("RepeatWeekdays","지정한 요일 같은 시간"),("AutoHide","알림 전까지 노트 자동 숨김"),("AutoHideDescription","알림이 울리면 노트가 다시 나타납니다."),("Sun","일"),("Mon","월"),("Tue","화"),("Wed","수"),("Thu","목"),("Fri","금"),("Sat","토"),
            ("CurrentNote","현재 노트"),("Font","글꼴"),("FontSize","글꼴 크기"),("Color","색상"),("PenColor","펜 색상"),("PenThickness","펜 굵기"),("PenThicknessInput","펜 굵기 숫자 입력 (1~10)"),("GeneralSettings","전체 설정"),("UseTray","시스템 트레이 사용"),("RunAtStartup","Windows 시작 시 실행"),("ReminderSound","리마인더 알람 소리"),("ReminderWavPath","리마인더 WAV 파일 경로"),("NewNoteHotKey","새 노트 전역 단축키"),("ToggleNotesHotKey","노트 표시/숨김 전역 단축키"),
            ("NewNote","새 노트"),("ShowAll","모두 표시"),("ShowAllHidden","모두 표시 ({0}개 숨겨짐)"),("HideAll","모두 숨기기"),("Exit","종료"),("DirtyExport","저장한 파일 이후 수정됨"),("AlwaysOnTop","항상 위"),("DisableAlwaysOnTop","항상 위 해제"),("Menu","메뉴"),("CloseNote","이 노트 닫기"),("Soon","곧 알림"),("RemainingDays","{0}일 {1}시간 {2}분 남음"),("RemainingHours","{0}시간 {1}분 남음"),("RemainingMinutes","{0}분 남음"),("RemainingSeconds","{0}초 남음"),
            ("TextMode","텍스트 모드"),("PenMode","펜 모드"),("EraserMode","지우개 모드"),("SyntaxHighlighting","구문 강조"),("AutoDetect","자동 감지"),("PlainText","일반 텍스트"),("SaveNote","현재 노트 저장"),("SaveAs","다른 이름으로 저장"),("HideNote","노트 숨기기"),("Undo","실행 취소"),("Redo","다시 실행"),("Cut","잘라내기"),("Copy","복사"),("Paste","붙여넣기"),("Delete","삭제"),("SelectAll","전체 선택"),
            ("NoteColor","노트 색상"),("Yellow","노랑"),("LightGreen","연두"),("SkyBlue","하늘색"),("Pink","분홍"),("Orange","주황"),("LightPurple","연보라"),("LightGray","연회색"),("Black","검정"),("DarkGray","진회색"),("Red","빨강"),("Blue","파랑"),("Green","초록"),("Purple","보라"),("VeryThin","매우 가늘게"),("Thin","가늘게"),("Normal","보통"),("Thick","굵게"),("VeryThick","매우 굵게"),
            ("UnexpectedError","작업을 처리하지 못했습니다. 로그를 확인해 주세요."),("PenThicknessError","펜 굵기는 1에서 10 사이의 숫자로 입력해 주세요."),("HotKeyError","단축키는 Ctrl+Alt+N과 같은 형식으로 입력해 주세요."),("SoundMissing","선택한 알람 소리 파일을 찾을 수 없습니다."),("FontSizeError","글꼴 크기는 8에서 72 사이의 숫자로 입력해 주세요."),("SelectAlarmSound","리마인더 알람 소리 선택"),("WavFilter","WAV 오디오 (*.wav)|*.wav"),("TimeError24","시는 0~23, 분은 0~59 사이로 입력해 주세요."),("TimeError12","시는 1~12, 분은 0~59 사이로 입력해 주세요."),("WeekdayError","반복할 요일을 하나 이상 선택해 주세요."),
            ("LargeTextError","5MB보다 큰 텍스트 파일은 삽입할 수 없습니다."),("ReadFileError","파일을 읽을 수 없습니다."),("OpenImageError","이미지를 열 수 없습니다."),("AttachmentMissing","첨부 파일을 찾을 수 없습니다."),("AttachmentOpenError","첨부 파일을 열 수 없습니다."),("SaveDialogTitle","현재 노트 저장"),("NaraNoteFilter","NaraNote 문서 (*.naranote)|*.naranote|텍스트 파일 (*.txt)|*.txt"),("TextFilter","텍스트 파일 (*.txt)|*.txt|NaraNote 문서 (*.naranote)|*.naranote"),("LossWarning","이 형식으로 저장하면 텍스트만 저장되며 드로잉, 이미지 및 첨부 개체는 파일에 포함되지 않습니다.\n\n계속 저장하시겠습니까?"),("ObjectsExcluded","개체가 제외됩니다"),("SaveError","현재 노트를 파일로 저장하지 못했습니다. 저장 위치와 파일 접근 권한을 확인해 주세요."),("ExternalChangedDirty","연결된 파일이 외부에서 변경되었습니다.\n\n다시 로드하면 현재 노트의 저장되지 않은 변경 내용이 대체됩니다. 다시 로드하시겠습니까?"),("ExternalChanged","연결된 파일이 외부에서 변경되었습니다. 다시 로드하시겠습니까?"),("ReloadError","변경된 파일을 다시 불러오지 못했습니다. 파일 형식과 접근 권한을 확인해 주세요.")),
        ["fr"] = Override(("Settings","Réglages"),("Ok","OK"),("Cancel","Annuler"),("Default","Par défaut"),("Browse","Parcourir…"),("Reminder","Rappel"),("ReminderEdit","Modifier le rappel…"),("ReminderMenu","Rappel…"),("ReminderDisable","Désactiver le rappel"),("ReminderDescription","Choisissez la date et l’heure du rappel."),("Date","Date"),("Time","Heure"),("Use24Hour","Format 24 h"),("AM","AM"),("PM","PM"),("Hour","Heure"),("Hour023","Heure (0–23)"),("Hour112","Heure (1–12)"),("Minute059","Minute (0–59)"),("Repeat","Répéter"),("RepeatOnce","Une fois"),("RepeatDaily","Tous les jours à la même heure"),("RepeatWeekly","Chaque semaine à la même heure"),("RepeatWeekdays","Certains jours à la même heure"),("AutoHide","Masquer la note jusqu’au rappel"),("AutoHideDescription","La note réapparaîtra au déclenchement du rappel."),("CurrentNote","Note actuelle"),("Font","Police"),("FontSize","Taille de police"),("Color","Couleur"),("PenColor","Couleur du stylo"),("PenThickness","Épaisseur du stylo"),("GeneralSettings","Réglages généraux"),("UseTray","Utiliser la zone de notification"),("RunAtStartup","Lancer au démarrage de Windows"),("ReminderSound","Son d’alarme du rappel"),("NewNoteHotKey","Raccourci global nouvelle note"),("ToggleNotesHotKey","Raccourci global afficher/masquer"),("NewNote","Nouvelle note"),("ShowAll","Tout afficher"),("ShowAllHidden","Tout afficher ({0} masquées)"),("HideAll","Tout masquer"),("Exit","Quitter"),("AlwaysOnTop","Toujours au premier plan"),("DisableAlwaysOnTop","Désactiver le premier plan"),("Menu","Menu"),("CloseNote","Fermer cette note"),("TextMode","Mode texte"),("PenMode","Mode stylo"),("EraserMode","Mode gomme"),("SyntaxHighlighting","Coloration syntaxique"),("AutoDetect","Détection automatique"),("PlainText","Texte brut"),("SaveNote","Enregistrer la note"),("SaveAs","Enregistrer sous"),("HideNote","Masquer la note"),("Undo","Annuler"),("Redo","Rétablir"),("Cut","Couper"),("Copy","Copier"),("Paste","Coller"),("Delete","Supprimer"),("SelectAll","Tout sélectionner"),("NoteColor","Couleur de la note"),("UnexpectedError","Impossible d’effectuer l’opération. Consultez le journal."),("TimeError24","Saisissez une heure de 0 à 23 et des minutes de 0 à 59."),("TimeError12","Saisissez une heure de 1 à 12 et des minutes de 0 à 59."),("WeekdayError","Sélectionnez au moins un jour."),("SaveDialogTitle","Enregistrer la note"),("LossWarning","Ce format n’enregistre que le texte. Les dessins, images et pièces jointes seront exclus.\n\nContinuer ?"),("ObjectsExcluded","Les objets seront exclus"),("SaveError","Impossible d’enregistrer la note. Vérifiez l’emplacement et les autorisations.")),
        ["es"] = Override(("Settings","Configuración"),("Ok","Aceptar"),("Cancel","Cancelar"),("Default","Predeterminado"),("Browse","Examinar…"),("Reminder","Recordatorio"),("ReminderEdit","Editar recordatorio…"),("ReminderMenu","Recordatorio…"),("ReminderDisable","Desactivar recordatorio"),("ReminderDescription","Elige cuándo quieres recibir el recordatorio."),("Date","Fecha"),("Time","Hora"),("Use24Hour","Formato de 24 horas"),("AM","a. m."),("PM","p. m."),("Hour","Hora"),("Hour023","Hora (0–23)"),("Hour112","Hora (1–12)"),("Minute059","Minuto (0–59)"),("Repeat","Repetir"),("RepeatOnce","Una vez"),("RepeatDaily","Cada día a la misma hora"),("RepeatWeekly","Cada semana a la misma hora"),("RepeatWeekdays","Días seleccionados a la misma hora"),("AutoHide","Ocultar nota hasta el recordatorio"),("AutoHideDescription","La nota reaparecerá cuando se active el recordatorio."),("CurrentNote","Nota actual"),("Font","Fuente"),("FontSize","Tamaño de fuente"),("Color","Color"),("PenColor","Color del lápiz"),("PenThickness","Grosor del lápiz"),("GeneralSettings","Configuración general"),("UseTray","Usar bandeja del sistema"),("RunAtStartup","Ejecutar al iniciar Windows"),("ReminderSound","Sonido de alarma"),("NewNoteHotKey","Atajo global para nueva nota"),("ToggleNotesHotKey","Atajo global para mostrar/ocultar"),("NewNote","Nueva nota"),("ShowAll","Mostrar todas"),("ShowAllHidden","Mostrar todas ({0} ocultas)"),("HideAll","Ocultar todas"),("Exit","Salir"),("AlwaysOnTop","Siempre visible"),("DisableAlwaysOnTop","Desactivar siempre visible"),("Menu","Menú"),("CloseNote","Cerrar esta nota"),("TextMode","Modo texto"),("PenMode","Modo lápiz"),("EraserMode","Modo borrador"),("SyntaxHighlighting","Resaltado de sintaxis"),("AutoDetect","Detección automática"),("PlainText","Texto sin formato"),("SaveNote","Guardar nota actual"),("SaveAs","Guardar como"),("HideNote","Ocultar nota"),("Undo","Deshacer"),("Redo","Rehacer"),("Cut","Cortar"),("Copy","Copiar"),("Paste","Pegar"),("Delete","Eliminar"),("SelectAll","Seleccionar todo"),("NoteColor","Color de nota"),("UnexpectedError","No se pudo completar la operación. Consulta el registro."),("TimeError24","Introduce una hora de 0 a 23 y minutos de 0 a 59."),("TimeError12","Introduce una hora de 1 a 12 y minutos de 0 a 59."),("WeekdayError","Selecciona al menos un día."),("SaveDialogTitle","Guardar nota actual"),("LossWarning","Este formato solo guarda texto. Los dibujos, imágenes y archivos adjuntos no se incluirán.\n\n¿Continuar?"),("ObjectsExcluded","Se excluirán los objetos"),("SaveError","No se pudo guardar la nota. Comprueba la ubicación y los permisos.")),
        ["vi"] = Override(("Settings","Cài đặt"),("Ok","OK"),("Cancel","Hủy"),("Default","Mặc định"),("Browse","Duyệt…"),("Reminder","Lời nhắc"),("ReminderEdit","Sửa lời nhắc…"),("ReminderMenu","Lời nhắc…"),("ReminderDisable","Tắt lời nhắc"),("ReminderDescription","Chọn ngày và giờ bạn muốn được nhắc."),("Date","Ngày"),("Time","Giờ"),("Use24Hour","Định dạng 24 giờ"),("AM","SA"),("PM","CH"),("Hour","Giờ"),("Hour023","Giờ (0–23)"),("Hour112","Giờ (1–12)"),("Minute059","Phút (0–59)"),("Repeat","Lặp lại"),("RepeatOnce","Một lần"),("RepeatDaily","Hằng ngày cùng giờ"),("RepeatWeekly","Hằng tuần cùng giờ"),("RepeatWeekdays","Các ngày đã chọn cùng giờ"),("AutoHide","Ẩn ghi chú đến khi nhắc"),("AutoHideDescription","Ghi chú sẽ xuất hiện lại khi lời nhắc kích hoạt."),("CurrentNote","Ghi chú hiện tại"),("Font","Phông chữ"),("FontSize","Cỡ chữ"),("Color","Màu"),("PenColor","Màu bút"),("PenThickness","Độ dày bút"),("GeneralSettings","Cài đặt chung"),("UseTray","Dùng khay hệ thống"),("RunAtStartup","Chạy khi Windows khởi động"),("ReminderSound","Âm báo lời nhắc"),("NewNoteHotKey","Phím tắt toàn cục tạo ghi chú"),("ToggleNotesHotKey","Phím tắt toàn cục hiện/ẩn"),("NewNote","Ghi chú mới"),("ShowAll","Hiện tất cả"),("ShowAllHidden","Hiện tất cả ({0} đang ẩn)"),("HideAll","Ẩn tất cả"),("Exit","Thoát"),("AlwaysOnTop","Luôn ở trên cùng"),("DisableAlwaysOnTop","Tắt luôn ở trên cùng"),("Menu","Trình đơn"),("CloseNote","Đóng ghi chú này"),("TextMode","Chế độ văn bản"),("PenMode","Chế độ bút"),("EraserMode","Chế độ tẩy"),("SyntaxHighlighting","Tô sáng cú pháp"),("AutoDetect","Tự động nhận diện"),("PlainText","Văn bản thuần"),("SaveNote","Lưu ghi chú hiện tại"),("SaveAs","Lưu thành"),("HideNote","Ẩn ghi chú"),("Undo","Hoàn tác"),("Redo","Làm lại"),("Cut","Cắt"),("Copy","Sao chép"),("Paste","Dán"),("Delete","Xóa"),("SelectAll","Chọn tất cả"),("NoteColor","Màu ghi chú"),("UnexpectedError","Không thể hoàn tất thao tác. Hãy kiểm tra nhật ký."),("TimeError24","Nhập giờ từ 0 đến 23 và phút từ 0 đến 59."),("TimeError12","Nhập giờ từ 1 đến 12 và phút từ 0 đến 59."),("WeekdayError","Chọn ít nhất một ngày trong tuần."),("SaveDialogTitle","Lưu ghi chú hiện tại"),("LossWarning","Định dạng này chỉ lưu văn bản. Hình vẽ, hình ảnh và tệp đính kèm sẽ không được lưu.\n\nTiếp tục?"),("ObjectsExcluded","Các đối tượng sẽ bị loại trừ"),("SaveError","Không thể lưu ghi chú. Hãy kiểm tra vị trí và quyền truy cập."))
    };

    static UiText()
    {
        Add("ko", ("Language","언어"),("SystemDefault","시스템 기본값"));
        Add("fr", ("Language","Langue"),("SystemDefault","Langue du système"));
        Add("es", ("Language","Idioma"),("SystemDefault","Idioma del sistema"));
        Add("vi", ("Language","Ngôn ngữ"),("SystemDefault","Ngôn ngữ hệ thống"));
        Add("fr", ("Sun","Dim"),("Mon","Lun"),("Tue","Mar"),("Wed","Mer"),("Thu","Jeu"),("Fri","Ven"),("Sat","Sam"),("DirtyExport","Modifiée depuis le fichier enregistré"),("Soon","Rappel imminent"),("RemainingDays","{0} j {1} h {2} min restantes"),("RemainingHours","{0} h {1} min restantes"),("RemainingMinutes","{0} min restantes"),("RemainingSeconds","{0} s restantes"),("Yellow","Jaune"),("LightGreen","Vert clair"),("SkyBlue","Bleu ciel"),("Pink","Rose"),("Orange","Orange"),("LightPurple","Violet clair"),("LightGray","Gris clair"),("Black","Noir"),("DarkGray","Gris foncé"),("Red","Rouge"),("Blue","Bleu"),("Green","Vert"),("Purple","Violet"),("VeryThin","Très fin"),("Thin","Fin"),("Normal","Normal"),("Thick","Épais"),("VeryThick","Très épais"),
            ("PenThicknessInput","Épaisseur du stylo (1–10)"),("ReminderWavPath","Chemin du fichier WAV du rappel"),("PenThicknessError","Saisissez une épaisseur de stylo entre 1 et 10."),("HotKeyError","Saisissez les raccourcis sous la forme Ctrl+Alt+N."),("SoundMissing","Le fichier audio sélectionné est introuvable."),("FontSizeError","Saisissez une taille de police entre 8 et 72."),("SelectAlarmSound","Choisir le son d’alarme"),("WavFilter","Audio WAV (*.wav)|*.wav"),("LargeTextError","Les fichiers texte de plus de 5 Mo ne peuvent pas être insérés."),("ReadFileError","Impossible de lire le fichier."),("OpenImageError","Impossible d’ouvrir l’image."),("AttachmentMissing","La pièce jointe est introuvable."),("AttachmentOpenError","Impossible d’ouvrir la pièce jointe."),("NaraNoteFilter","Document NaraNote (*.naranote)|*.naranote|Fichier texte (*.txt)|*.txt"),("TextFilter","Fichier texte (*.txt)|*.txt|Document NaraNote (*.naranote)|*.naranote"),("ExternalChangedDirty","Le fichier lié a été modifié hors de NaraNote.\n\nLe rechargement remplacera les modifications non enregistrées. Recharger ?"),("ExternalChanged","Le fichier lié a été modifié hors de NaraNote. Recharger ?"),("ReloadError","Impossible de recharger le fichier modifié. Vérifiez son format et ses autorisations."));
        Add("es", ("Sun","Dom"),("Mon","Lun"),("Tue","Mar"),("Wed","Mié"),("Thu","Jue"),("Fri","Vie"),("Sat","Sáb"),("DirtyExport","Modificada desde el archivo guardado"),("Soon","Recordatorio próximo"),("RemainingDays","Quedan {0} d {1} h {2} min"),("RemainingHours","Quedan {0} h {1} min"),("RemainingMinutes","Quedan {0} min"),("RemainingSeconds","Quedan {0} s"),("Yellow","Amarillo"),("LightGreen","Verde claro"),("SkyBlue","Azul cielo"),("Pink","Rosa"),("Orange","Naranja"),("LightPurple","Violeta claro"),("LightGray","Gris claro"),("Black","Negro"),("DarkGray","Gris oscuro"),("Red","Rojo"),("Blue","Azul"),("Green","Verde"),("Purple","Morado"),("VeryThin","Muy fino"),("Thin","Fino"),("Normal","Normal"),("Thick","Grueso"),("VeryThick","Muy grueso"),
            ("PenThicknessInput","Grosor del lápiz (1–10)"),("ReminderWavPath","Ruta del archivo WAV del recordatorio"),("PenThicknessError","Introduce un grosor de lápiz entre 1 y 10."),("HotKeyError","Introduce los atajos con un formato como Ctrl+Alt+N."),("SoundMissing","No se encontró el archivo de sonido seleccionado."),("FontSizeError","Introduce un tamaño de fuente entre 8 y 72."),("SelectAlarmSound","Seleccionar sonido de alarma"),("WavFilter","Audio WAV (*.wav)|*.wav"),("LargeTextError","No se pueden insertar archivos de texto mayores de 5 MB."),("ReadFileError","No se pudo leer el archivo."),("OpenImageError","No se pudo abrir la imagen."),("AttachmentMissing","No se encontró el archivo adjunto."),("AttachmentOpenError","No se pudo abrir el archivo adjunto."),("NaraNoteFilter","Documento NaraNote (*.naranote)|*.naranote|Archivo de texto (*.txt)|*.txt"),("TextFilter","Archivo de texto (*.txt)|*.txt|Documento NaraNote (*.naranote)|*.naranote"),("ExternalChangedDirty","El archivo vinculado cambió fuera de NaraNote.\n\nRecargarlo reemplazará los cambios no guardados. ¿Recargar?"),("ExternalChanged","El archivo vinculado cambió fuera de NaraNote. ¿Recargar?"),("ReloadError","No se pudo recargar el archivo modificado. Comprueba el formato y los permisos."));
        Add("vi", ("Sun","CN"),("Mon","T2"),("Tue","T3"),("Wed","T4"),("Thu","T5"),("Fri","T6"),("Sat","T7"),("DirtyExport","Đã sửa sau lần lưu tệp"),("Soon","Sắp đến giờ nhắc"),("RemainingDays","Còn {0} ngày {1} giờ {2} phút"),("RemainingHours","Còn {0} giờ {1} phút"),("RemainingMinutes","Còn {0} phút"),("RemainingSeconds","Còn {0} giây"),("Yellow","Vàng"),("LightGreen","Xanh lá nhạt"),("SkyBlue","Xanh da trời"),("Pink","Hồng"),("Orange","Cam"),("LightPurple","Tím nhạt"),("LightGray","Xám nhạt"),("Black","Đen"),("DarkGray","Xám đậm"),("Red","Đỏ"),("Blue","Xanh dương"),("Green","Xanh lá"),("Purple","Tím"),("VeryThin","Rất mảnh"),("Thin","Mảnh"),("Normal","Bình thường"),("Thick","Dày"),("VeryThick","Rất dày"),
            ("PenThicknessInput","Độ dày bút (1–10)"),("ReminderWavPath","Đường dẫn tệp WAV lời nhắc"),("PenThicknessError","Nhập độ dày bút từ 1 đến 10."),("HotKeyError","Nhập phím tắt theo định dạng như Ctrl+Alt+N."),("SoundMissing","Không tìm thấy tệp âm thanh đã chọn."),("FontSizeError","Nhập cỡ chữ từ 8 đến 72."),("SelectAlarmSound","Chọn âm báo lời nhắc"),("WavFilter","Âm thanh WAV (*.wav)|*.wav"),("LargeTextError","Không thể chèn tệp văn bản lớn hơn 5 MB."),("ReadFileError","Không thể đọc tệp."),("OpenImageError","Không thể mở hình ảnh."),("AttachmentMissing","Không tìm thấy tệp đính kèm."),("AttachmentOpenError","Không thể mở tệp đính kèm."),("NaraNoteFilter","Tài liệu NaraNote (*.naranote)|*.naranote|Tệp văn bản (*.txt)|*.txt"),("TextFilter","Tệp văn bản (*.txt)|*.txt|Tài liệu NaraNote (*.naranote)|*.naranote"),("ExternalChangedDirty","Tệp liên kết đã thay đổi bên ngoài NaraNote.\n\nTải lại sẽ thay thế các thay đổi chưa lưu. Tải lại?"),("ExternalChanged","Tệp liên kết đã thay đổi bên ngoài NaraNote. Tải lại?"),("ReloadError","Không thể tải lại tệp đã thay đổi. Hãy kiểm tra định dạng và quyền truy cập."));
    }

    private static void Add(string language, params (string Key, string Value)[] values)
    {
        foreach (var (key, value) in values) Catalog[language][key] = value;
    }

    private static Dictionary<string, string> Override(params (string Key, string Value)[] values) => values.ToDictionary(item => item.Key, item => item.Value);
}

[MarkupExtensionReturnType(typeof(string))]
public sealed class LocExtension(string key) : MarkupExtension
{
    public string Key { get; } = key;
    public override object ProvideValue(IServiceProvider serviceProvider) => UiText.Get(Key);
}
